# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bc2b0718a9c29ccf2ecf1ced510edc006df21447224b6ad25b57882bcecec6e50a4de6d6b3adea3ef24179f51b61ae36e5dd45bc973eb60b0dd23d118125571

test:
  secret_key_base: b558303ceb1412be5c48e7c81868d9e08073c7cd6fabfc9622b6c8620a7435ba16a82ba938b48dabc5c0e884d5019d81acef11b448daf7d5555178bfe58153ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
